version: '3'
services:
  front:
    build: .
    image: car-fleet_angular
    container_name: car-fleet_front
    command: sh -c "${CAR_FLEET_COMMAND:-npm start}"
    ports:
      - 4200:4200
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
volumes:
  node_modules:
